package com.mislbd.ababil.treasury.domain;

public enum GLType {
    PRODUCT_GL, RECEIVING_ACCOUNT, PAYING_ACCOUNT, TXN_AMOUNT, ACTUAL_PROFIT_AMOUNT,
    PROVISIONAL_PROFIT_AMOUNT, EXPENDITURE_TAX, TAX_RATE, ACCOUNT,
    EXCISE_DUTY_AMOUNT, TAX_AMOUNT, INCOME_GL, PROFIT_RECEIVABLE_GL, GENERAL_ACCOUNT_GL,
    SETTLEMENT_ACCOUNT, EXPENDITURE_GL, EXCISE_DUTY_GL, TAX_GL, ADVANCE_TAX_GL,
    PAYABLE_GL, CHARGE_GL, SERVICE_CHARGE_AMOUNT
}
